#!/bin/bash

. /utils.sh

case $cmd in
	start)
		yum install python-pip python2.7-elementtree -y
		pip install pip --upgrade
		pip install pan-python
		wget https://raw.githubusercontent.com/datacenter/cloudcenter-content/${panext_gitTag}/services/panext/service-pan.py
		python service-pan.py start
		#$OSSVC_HOME/$SVCNAME/service-pan.py start

		serviceStatus="Started"
		;;
	stop)
		serviceStatus="Stopped"
		;;
	update)
		serviceStatus="Updated"
		;;
	*)
		serviceStatus="No Valid Script Argument"
		exit 127
		;;
esac

#result="{\"hostName\": \"example.com\", \"ipAddress\": \"192.168.1.8\", \"environment\":{\"instanceName\": \"test_instance\", \"instanceType\":\"dummy\", \"serviceType\": \"custom\", \"serviceStatus\":\"$serviceStatus\"}}"
result="{\"hostName\": \"$serviceStatus\", \"ipAddress\": \"192.168.1.8\"}"
# echo $result
print_ext_service_result "$result"
print_error "something wrong"
