#!/bin/bash
. /utils.sh

env

cmd=$1
serviceStatus=""


case $CloudFamily in
	AzureRM)
		# Setup a bunch of prerequisits
		yum install gcc git python-pip python-devel -y
		pip install --upgrade pip
		pip install msrest msrestazure
		pip install --pre azure 

		#Random sed thing to fix tiny error in msrest library.
		sed -i -re "s/len\(self.data\)/str\(len\(self.data\)\)/g" /usr/lib/python2.7/site-packages/msrest/pipeline.py


		wget -N https://raw.githubusercontent.com/datacenter/cloudcenter-content/master/services/sqlserverpaas/sqlserverpaas-arm.py

		case $cmd in
			start)
				print_log "$(python sqlserverpaas-arm.py start)"
				serviceStatus="Started"
				;;
			stop)
				print_log "$(python sqlserverpaas-arm.py stop)"
				serviceStatus="Stopped"
				;;
			*)
				serviceStatus="No Valid Script Argument"
				exit 127
				;;
		esac
		;;
	*)
		exit 127
		print_error "Not deployed to supported cloud. Currently only Azure Resource Manager supported."
		;;
esac

