#!/bin/bash

# Make sure to source these files to pick up all the CliQr environment variables.
. /usr/local/osmosix/etc/.osmosix.sh
. /usr/local/osmosix/etc/userenv


# After triggered reboot, CliQr agent generates file $OSMOSIX_PROD_HOME/.cliqrRebootResumeInit
# with prior state from /tmp/.cliqrRebootResumeInit

# If this file DOES NOT exist, it means that this is the first pass through the script.
# The CliQr agent has not previously triggered a reboot and created this file.
if [ ! -e $OSMOSIX_PROD_HOME/.cliqrRebootResumeInit ];
then
	# Node was not rebooted already by CliQr nodeInit. First pass through this script.


	# Triggers a reboot after the script exits, then this file is deleted.
	# "Step 2" will now appear in $OSMOSIX_PROD_HOME/.cliqrRebootResumeInit
	echo "Part 2" > /tmp/.cliqrRebootResumeInit

else
	# Node was rebooted on the last pass through the script.
	# Read in prior state from file generated by CliQr
	step=`cat $OSMOSIX_PROD_HOME/.cliqrRebootResumeInit`

	# Check the prior state to continue with the next part of the script.
	case $step in
		"Part 2")

			# Triggers a reboot after the script exits, then this file is deleted.
			# "Step 3" will now appear in $OSMOSIX_PROD_HOME/.cliqrRebootResumeInit
			echo "Part 3" > /tmp/.cliqrRebootResumeInit
			;;
		"Part 3")
			# Don't write to /tmp/.cliqrRebootResumeInit this time. CliQr will not reboot.
			# Script exists, and node init is complete.
			;;
	esac
fi

