#!/bin/bash

# lambda service script

exec > >(tee -a /usr/local/osmosix/logs/service.log) 2>&1

. /utils.sh


# Print the env to the CCM UI for debugging. Remove this line for production.
# Ues with:
# sed -n '/718WPR53 ENV START/,/718WPR53 ENV END/p' /usr/local/cliqr/logs/gateway.log | \
# head -n-1 | tail -n+2 | grep '=' | grep -v '\\n' > envfile
#echo "${parentJobName} ENV START"
#env
#echo "${parentJobName} ENV END"

cmd=$1
SVCNAME="lambda1"
export INSTALL_DIR="/usr/local/aws"

if [ -n "${gitTag}" ]; then
    tag="${gitTag}"
else
    tag="lambda"
fi

print_log "Tag/branch for code pull set to ${tag}"

error () {
    print_log "${1}"
    exit 1
}

# the following should be parameters from the service

if [ -z "$lambdaFunctionName" ];
then
	export functionName="lambda-"$currentTierJobId;
fi

if [ -z "$lambdaRuntime" ];
then
	error "Runtime missing for Lambda function"
fi

if [ -z "$lambdaHandler" ];
then
	error "Handler missing for Lambda function"
fi

if [ -z "$lambdaRole" ];
then
	error "Role missing for Lambda function"
fi

if [ -z "$lambdaCodeS3Bucket" ];
then
	error "S3 Bucket containing function code missing"
fi

if [ -z "$lambdaCodeS3Key" ];
then
	error "S3 Key containing function code missing"
fi

if [ ! -z "$lambdaRegion" ];
then
	region=$lambdaRegion;
fi

if [ ! -z "$region" ];
then
	region="us-east-1";
fi


installAWSCli() {

    print_log "Installing AWS CLI tools..."

	if [ -d $INSTALL_DIR ]; then
			echo  "AWS Cli already installed skipping the AWS Cli Install";
			export PATH=$PATH:$INSTALL_DIR/bin
			echo "PATH value is = $PATH"
	else
			mkdir -p $INSTALL_DIR
			cd $INSTALL_DIR
			wget http://s3.amazonaws.com/aws-cli/awscli-bundle.zip
			unzip awscli-bundle.zip
			./awscli-bundle/install -i $INSTALL_DIR
			rm -f awscli-bundle.zip
			export PATH=$PATH:$INSTALL_DIR/bin
			echo "PATH value is = $PATH"
	fi

}


configureAWSCli(){
    print_log "Configuring AWS CLI..."
	export JAVA_HOME="/usr/lib/jvm/jre"
	export EC2_REGION="$region"
	export PATH=$PATH:$INSTALL_DIR/bin

	if [ ! -z "$lambdaAWSkey" ] && [ ! -z "$lambdaAWSsecretkey" ];
	then
		export AWS_ACCESS_KEY_ID="$lambdaAWSkey"
		export AWS_SECRET_ACCESS_KEY="$lambdaAWSsecretkey"

	elif [ -z $CliqrCloudAccountPwd ] || [ -z $CliqrCloud_AccessSecretKey ];
	then
		error "Insufficient permissions to access the Cloud Account, contact your Admin for the Cloud Account Accessibility";
	else
		export AWS_ACCESS_KEY_ID="$CliqrCloudAccountPwd"
		export AWS_SECRET_ACCESS_KEY="$CliqrCloud_AccessSecretKey"

	fi

	if [ -z $AWS_ACCESS_KEY_ID ];then
			error "Cloud Account Access Key not found or couldn't generate with IAM role"
	fi

	if [ -z $AWS_SECRET_ACCESS_KEY ];then
			error "Cloud Account Secret Key not found or couldn't generate with IAM role"
	fi

	if [ -z $region ];then
			error "Region Value is not set"
	fi

	export "AWS_DEFAULT_REGION"=$region

}


createLambdaFunction(){

    command="aws --no-verify-ssl lambda create-function --function-name $lambdaFunctionName --runtime $lambdaRuntime --handler $lambdaHandler --role $lambdaRole --code S3Bucket=$lambdaCodeS3Bucket,S3Key=$lambdaCodeS3Key 2>&1"

    print_log $command

    msg=$(${command} 2>&1) || \
        error "Failed to create Lambda function: ${msg}"

    print_log "Successfully created the Lambda function $lambdaFunctionName"

}

deleteLambdaFunction(){

    command="aws lambda delete-function --function-name $lambdaFunctionName"

    print_log $command

    msg=$(${command} 2>&1) || \
        error "Failed to delete Lambda function: ${msg}"

    print_log "Successfully deleted the Lambda function $lambdaFunctionName"

}


case $cmd in
	start)
		echo "Service Action -  $cmd"
		echo "Installing AWS Cli Tools"
		installAWSCli
		configureAWSCli
		createLambdaFunction
		exit 0
		;;
	stop)
		echo "Service Action -  $cmd"
        echo "Installing AWS Cli Tools"
        installAWSCli
        configureAWSCli
		deleteLambdaFunction
        	exit 0
		;;
	suspend)
		echo "Service Action -  $cmd"
		echo "Installing AWS Cli Tools"
		installAWSCli
        configureAWSCli
		deleteLambdaFunction
		exit 0
		;;
	resume)
		echo "Service Action -  $cmd"
		echo "Installing AWS Cli Tools"
		installAWSCli
        configureAWSCli
		createLambdaFunction
		exit 0
		;;
	*)
		echo "unknown command"
		exit 127
		;;
esac
