#!/bin/bash
#F5 External Service Script

#For VM-based service
#OSSVC_HOME=/usr/local/osmosix/service
#. /usr/local/osmosix/etc/.osmosix.sh
#. /usr/local/osmosix/etc/userenv
#. $OSSVC_HOME/utils/cfgutil.sh
#. $OSSVC_HOME/utils/install_util.sh
#. $OSSVC_HOME/utils/os_info_util.sh
#. /usr/local/osmosix/service/utils/agent_util.sh

#For external-service
env
#. /utils.sh

cmd=$1
serviceStatus=""
SVCNAME=$OSSVC_CONFIG
SVCHOME="$OSSVC_HOME/$OSSVC_CONFIG"
USER_ENV="/usr/local/osmosix/etc/userenv"


#print_ext_service_result "{foo:bar}"

yum install -y epel-release
yum install -y python-pip wget

case $lbType in
	elb)
		pip install requests boto3 --upgrade

		#Configure AWS creds for boto
		mkdir -p ~/.aws
		echo "[default]" > ~/.aws/config
		echo "region=us-west-2" >> ~/.aws/config
		echo "output=json" >> ~/.aws/config
		echo "[default]" > ~/.aws/credentials
		echo "aws_access_key_id=$aws_access_key_id" >> ~/.aws/credentials
		echo "aws_secret_access_key=$aws_secret_access_key" >> ~/.aws/credentials

		wget https://cliqrdemo-repo.s3.amazonaws.com/services/f5ext/elb.py -O elb.py

		case $cmd in
			start)
				serviceStatus="Starting"
				python elb.py start

				serviceStatus="Started"
				;;
			stop)
				serviceStatus="Stopping"
				python elb.py stop
				serviceStatus="Stopped"
				;;
			update)
				serviceStatus="Updating"
				python elb.py reload
				serviceStatus="Updated"
				;;
			*)
				serviceStatus="No Valid Script Argument"
				exit 127
				;;
		esac
		;;
	f5)
		pip install requests bigsuds --upgrade
		wget https://cliqrdemo-repo.s3.amazonaws.com/services/f5ext/f5.py -O f5.py
		case $cmd in
			start)
				serviceStatus="Starting"
				python f5.py start

				serviceStatus="Started"
				;;
			stop)
				serviceStatus="Stopping"
				python f5.py stop
				serviceStatus="Stopped"
				;;
			update)
				serviceStatus="Updating"
				python f5.py reload
				serviceStatus="Updated"
				;;
			*)
				serviceStatus="No Valid Script Argument"
				exit 127
				;;
		esac
		;;
	*)
		serviceStatus="No Valid LB Type Selected"
		exit 127
		;;
esac
