#!/bin/bash
. /utils.sh

env

cmd=$1
serviceStatus=""

case $cmd in
    update)
        ;;
    start)
        print_log("log1")
        ;;
    stop)
        ;;
    suspend)
        ;;
    resume)
        ;;
    *)
        serviceStatus="No Valid Script Argument"
        exit 127
        ;;
esac
