#!/bin/bash
. /utils.sh

env

cmd=$1
serviceStatus=""

print_log "Begining Service Script"

case $cmd in
    update)
        ;;
    start)
        print_log "Begining Start"
        print_log "Start Complete"
        ;;
    stop)
        ;;
    suspend)
        ;;
    resume)
        ;;
    *)
        serviceStatus="No Valid Script Argument"
        exit 127
        ;;
esac
print_log "Ending Service Script"