#!/bin/bash
. /utils.sh

env
print_log "$(env)"

if [ -n $gitTag ]; then
    tag=$gitTag
else
    tag="clean"
fi

print_log "Tag/branch for code pull set to $tag"

cmd=$1
serviceStatus=""

print_log "Beginning Service Script"

# print_log "Downloading dummyext.py"
# wget -N --no-check-certificate https://raw.githubusercontent.com/datacenter/cloudcenter-content/${tag}/services/dummyext/dummyext.py

case $cmd in
    update)
        ;;
    start)
        print_log "Begining Start"
        print_log "Executing dummyext.py"
        # python dummyext.py start
        print_log "Start Complete"
        ;;
    stop)
        ;;
    suspend)
        ;;
    resume)
        ;;
    *)
        serviceStatus="No Valid Script Argument"
        exit 127
        ;;
esac
print_log "Ending Service Script"